[versions]

activity-compose = "1.6.1"
compose = "1.3.0"
composeMaterial3 = "1.0.0"

[libraries]

activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "composeMaterial3" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-test-junit = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-ui-util = { module = "androidx.compose.ui:ui-util", version.ref = "compose" }

[bundles]

compose-ui = [
    "compose-material-icons-extended",
    "compose-material3",
    "compose-ui",
    "compose-ui-util",
    "compose-ui-tooling-preview",
]

compose-ui-debug = [
    "compose-ui-tooling",
    "compose-ui-test-manifest",
]