package com.adammcneilly.pocketleague.core.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFa9361e)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFffdad1)
val md_theme_light_onPrimaryContainer = Color(0xFF3f0400)
val md_theme_light_secondary = Color(0xFF775750)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFffdad1)
val md_theme_light_onSecondaryContainer = Color(0xFF2c1510)
val md_theme_light_tertiary = Color(0xFF6e5d2e)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFf8e0a6)
val md_theme_light_onTertiaryContainer = Color(0xFF241a00)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfcfcfc)
val md_theme_light_onBackground = Color(0xFF201a19)
val md_theme_light_surface = Color(0xFFfcfcfc)
val md_theme_light_onSurface = Color(0xFF201a19)
val md_theme_light_surfaceVariant = Color(0xFFf5ddd8)
val md_theme_light_onSurfaceVariant = Color(0xFF534340)
val md_theme_light_outline = Color(0xFF86736f)
val md_theme_light_inverseOnSurface = Color(0xFFfbeeeb)
val md_theme_light_inverseSurface = Color(0xFF362f2d)

val md_theme_dark_primary = Color(0xFFffb4a2)
val md_theme_dark_onPrimary = Color(0xFF650b00)
val md_theme_dark_primaryContainer = Color(0xFF891e07)
val md_theme_dark_onPrimaryContainer = Color(0xFFffdad1)
val md_theme_dark_secondary = Color(0xFFe7bdb4)
val md_theme_dark_onSecondary = Color(0xFF442a24)
val md_theme_dark_secondaryContainer = Color(0xFF5d3f38)
val md_theme_dark_onSecondaryContainer = Color(0xFFffdad1)
val md_theme_dark_tertiary = Color(0xFFdbc48c)
val md_theme_dark_onTertiary = Color(0xFF3d2f05)
val md_theme_dark_tertiaryContainer = Color(0xFF544519)
val md_theme_dark_onTertiaryContainer = Color(0xFFf8e0a6)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF201a19)
val md_theme_dark_onBackground = Color(0xFFede0dd)
val md_theme_dark_surface = Color(0xFF201a19)
val md_theme_dark_onSurface = Color(0xFFede0dd)
val md_theme_dark_surfaceVariant = Color(0xFF534340)
val md_theme_dark_onSurfaceVariant = Color(0xFFd8c2bd)
val md_theme_dark_outline = Color(0xFFa08d89)
val md_theme_dark_inverseOnSurface = Color(0xFF201a19)
val md_theme_dark_inverseSurface = Color(0xFFede0dd)
