name: Android App Tests

on:
  pull_request:

jobs:
  android-app-tests:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Generate local.properties
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: echo $LOCAL_PROPERTIES > ./local.properties

      - name: Run Tests
        run: ./gradlew app:pixelPhoneAndTabletGroupDebugAndroidTest
