name: Compile Code

on:
  push:
    branches:
      - development
  pull_request:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Generate local.properties
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: echo $LOCAL_PROPERTIES > ./local.properties

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          # Only write to the cache for builds on the 'development' branch
          cache-read-only: ${{ github.ref != 'refs/heads/development' }}

      - name: Compile
        run: |
          ./gradlew compileDebugKotlin
          ./gradlew compileReleaseKotlin

        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
