name: Compile Code

on:
  push:
    branches:
      - development
  pull_request:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/setup.yml

      - name: Compile
        run: |
          ./gradlew compileDebugKotlin
          ./gradlew compileReleaseKotlin

        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
