name: Lint Checks

on:
  push:
    branches:
      - development
  pull_request:

jobs:
  lint-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/setup.yml

      - name: Lint Checks
        run: ./gradlew detektAll lintKotlin android:app:lint