name: Paparazzi Tests

on:
  push:
    branches:
      - development
  pull_request:

jobs:
  paparazzi-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/setup.yml

      - name: Run Tests
        run: ./gradlew verifyPaparazziDebug