name: Unit Tests

on: pull_request

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.17

      - name: Generate local.properties
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: echo $LOCAL_PROPERTIES > ./local.properties

      - name: Build Project
        run: |
          ./gradlew check
          ./gradlew android:app:test