name: Unit Tests

on:
  push:
    branches:
      - development
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/setup.yml

      - name: Build Project
        run: |
          ./gradlew allTests
          ./gradlew android:app:test